vaspConfig:
  whisperNodeUrl: 
  contractNodeUrl: 
  vaspCode: 
  handshakePrivateKey: 
  signingPrivateKey: 
  vaspInfo:
    name: VASP-name
    id: 
    pk: 
    address:
      street: 
      number: 
      adrline: 
      postcode:
      town: 
      country: 
  acknowledgmentEnabled: false
infuraSecret: 
httpBasicAuth:
  name: 
  password: 


