vaspConfig:
  whisperNodeUrl: http://{host}:8545
  contractNodeUrl: https://ropsten.infura.io/v3/1d2e97e9b2344fcdae27e3763f866664
  vaspCode: 7dface61
  handshakePrivateKey:
  signingPrivateKey:
  vaspInfo:
    name: VASP-1
    id:
    pk:
      address:
      street: Vaspstreet
      number: 1
      adrline: Building 1
      postcode: 11111
      town: Vasptown
      country: US
  acknowledgmentEnabled: false
infuraSecret:
httpBasicAuth:
  name:
  password:
